//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.21 at 12:51:00 PM CAT 
//


package org.esaude.dmt.config.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="matching_input" type="{http://schema.config.dmt.esaude.org}fileType"/>
 *         &lt;element name="targetDs" type="{http://schema.config.dmt.esaude.org}datasourceType"/>
 *         &lt;element name="sourceDs" type="{http://schema.config.dmt.esaude.org}datasourceType" maxOccurs="unbounded"/>
 *         &lt;element name="log_output" type="{http://schema.config.dmt.esaude.org}fileType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "matchingInput",
    "targetDs",
    "sourceDs",
    "logOutput"
})
@XmlRootElement(name = "config")
public class Config {

    @XmlElement(name = "matching_input", required = true)
    protected FileType matchingInput;
    @XmlElement(required = true)
    protected DatasourceType targetDs;
    @XmlElement(required = true)
    protected List<DatasourceType> sourceDs;
    @XmlElement(name = "log_output", required = true)
    protected FileType logOutput;

    /**
     * Gets the value of the matchingInput property.
     * 
     * @return
     *     possible object is
     *     {@link FileType }
     *     
     */
    public FileType getMatchingInput() {
        return matchingInput;
    }

    /**
     * Sets the value of the matchingInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileType }
     *     
     */
    public void setMatchingInput(FileType value) {
        this.matchingInput = value;
    }

    /**
     * Gets the value of the targetDs property.
     * 
     * @return
     *     possible object is
     *     {@link DatasourceType }
     *     
     */
    public DatasourceType getTargetDs() {
        return targetDs;
    }

    /**
     * Sets the value of the targetDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatasourceType }
     *     
     */
    public void setTargetDs(DatasourceType value) {
        this.targetDs = value;
    }

    /**
     * Gets the value of the sourceDs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceDs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceDs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatasourceType }
     * 
     * 
     */
    public List<DatasourceType> getSourceDs() {
        if (sourceDs == null) {
            sourceDs = new ArrayList<DatasourceType>();
        }
        return this.sourceDs;
    }

    /**
     * Gets the value of the logOutput property.
     * 
     * @return
     *     possible object is
     *     {@link FileType }
     *     
     */
    public FileType getLogOutput() {
        return logOutput;
    }

    /**
     * Sets the value of the logOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileType }
     *     
     */
    public void setLogOutput(FileType value) {
        this.logOutput = value;
    }

}
