//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.07 at 01:33:19 PM CAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schema.config.dmt.esaude.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.esaude.dmt.config.schema;
