//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.18 at 01:21:29 PM CAT 
//


package org.esaude.matchingschema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for referenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="referenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="referencee" type="{http://esaude.org/matchingschema}referenceSideType"/>
 *         &lt;element name="referenced" type="{http://esaude.org/matchingschema}referenceSideType"/>
 *         &lt;element name="name_desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isDirect" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="predecessor" type="{http://esaude.org/matchingschema}referenceType"/>
 *         &lt;element name="referencedValue" type="{http://esaude.org/matchingschema}referencedValueType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "referenceType", propOrder = {
    "referencee",
    "referenced",
    "nameDesc",
    "isDirect",
    "predecessor",
    "referencedValue"
})
public class ReferenceType {

    @XmlElement(required = true)
    protected ReferenceSideType referencee;
    @XmlElement(required = true)
    protected ReferenceSideType referenced;
    @XmlElement(name = "name_desc", required = true)
    protected String nameDesc;
    protected boolean isDirect;
    @XmlElement(required = true)
    protected ReferenceType predecessor;
    @XmlElement(required = true)
    protected ReferencedValueType referencedValue;

    /**
     * Gets the value of the referencee property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceSideType }
     *     
     */
    public ReferenceSideType getReferencee() {
        return referencee;
    }

    /**
     * Sets the value of the referencee property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceSideType }
     *     
     */
    public void setReferencee(ReferenceSideType value) {
        this.referencee = value;
    }

    /**
     * Gets the value of the referenced property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceSideType }
     *     
     */
    public ReferenceSideType getReferenced() {
        return referenced;
    }

    /**
     * Sets the value of the referenced property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceSideType }
     *     
     */
    public void setReferenced(ReferenceSideType value) {
        this.referenced = value;
    }

    /**
     * Gets the value of the nameDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameDesc() {
        return nameDesc;
    }

    /**
     * Sets the value of the nameDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameDesc(String value) {
        this.nameDesc = value;
    }

    /**
     * Gets the value of the isDirect property.
     * 
     */
    public boolean isIsDirect() {
        return isDirect;
    }

    /**
     * Sets the value of the isDirect property.
     * 
     */
    public void setIsDirect(boolean value) {
        this.isDirect = value;
    }

    /**
     * Gets the value of the predecessor property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getPredecessor() {
        return predecessor;
    }

    /**
     * Sets the value of the predecessor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setPredecessor(ReferenceType value) {
        this.predecessor = value;
    }

    /**
     * Gets the value of the referencedValue property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedValueType }
     *     
     */
    public ReferencedValueType getReferencedValue() {
        return referencedValue;
    }

    /**
     * Sets the value of the referencedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedValueType }
     *     
     */
    public void setReferencedValue(ReferencedValueType value) {
        this.referencedValue = value;
    }

}
